import MainPage from './MainPage/MainPage';
import NotFound404 from './NotFound404/NotFound404';
import LoginPage from './LoginPage/LoginPage';
import RegisterPage from './RegisterPage/RegisterPage';
import ForgotPasswordPage from './ForgotPassword/ForgotPassword';
import RestorePasswordPage from './RestorePassword/RestorePassword';
import ProfilePagePage from './ProfilePage/ProfilePage';
import IngredientPage from './IngredientPage/IngredientPage';
import OrderPage from './OrderPage/OrderPage';
import OrderInfoPage from './OrderInfoPage/OrderInfoPage';
export {MainPage,NotFound404,LoginPage, RegisterPage,ForgotPasswordPage,RestorePasswordPage,ProfilePagePage, IngredientPage,OrderPage,OrderInfoPage}